### ISSUE TITLE
When loading trained model

### ISSUE THREAD

**Issue by LuweiZhang-UTokyo** [gusye1234/LightGCN-PyTorch#32]
When setting --pretrain as 1 (loading the trained model such as 'lgn-gowalla-3-64.pth.tar'), the initial of lgn model faces the problem:
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    Recmodel = register.MODELS[world.model_name](world.config, dataset)
  File "./LightGCN/code/model.py", line 90, in __init__
    self.__init_weight()
  File "./LightGCN/code/model.py", line 112, in __init_weight
    self.embedding_user.weight.data.copy_(torch.from_numpy(self.config['user_emb']))
KeyError: 'user_emb'

It seems that there is no statement of the config['user_emb'] and config['item_emb']  in world.py or anywhere.
Would you kindly like to tell me how to fix this part? How to load the trained model correctly?

**Comment by Rah1m2** [comment]
I also have this problem, have you solved it now?
